import os
import subprocess


@data_loader
def generate_ssh_key_pair(*args, **kwargs):
    """
    Generate an SSH key pair using ssh-keygen with the specified email.
    Outputs the paths to the private and public key files.

    Args:
        email (str): Email associated with the SSH key.
        key_type (str): Type of SSH key to generate, default is 'ed25519'.
        key_comment (str): Comment for the SSH key.

    Returns:
        Tuple[str, str]: Paths to the private and public SSH key files.
    """

    # Define the directory to store SSH keys
    email: str = "freem111@gmail.com"
    key_type: str = "ed25519"
    key_comment: str = "Generated by Mage Pro"
    ssh_dir = os.path.expanduser("~/.ssh")
    os.makedirs(ssh_dir, exist_ok=True)

    # Define the key file paths
    private_key_path = os.path.join(ssh_dir, "id_ed25519_mage")
    public_key_path = f"{private_key_path}.pub"

    # Check if key already exists to avoid overwriting
    if os.path.exists(private_key_path) or os.path.exists(public_key_path):
        raise FileExistsError(
            "SSH key files already exist. Please remove or specify a different filename."
        )

    # Build the ssh-keygen command
    command = [
        "ssh-keygen",
        "-t",
        key_type,
        "-C",
        key_comment,
        "-f",
        private_key_path,
        "-N",
        "",  # No passphrase
    ]

    # Execute the command
    subprocess.run(command, check=True)

    # Return the paths to the generated keys
    return private_key_path, public_key_path
